#!/usr/bin/env bash

set -e

echo "It is expected that this image is to be used in a chained s2i build."
echo "Running this image is only recommended during development or for testing purposes."
echo "To run this directly, you must specify the DEV_MODE=true environment variable."
echo "https://docs.okd.io/latest/dev_guide/builds/advanced_build_operations.html#dev-guide-chaining-builds"

npm run serve

# # Allow debugging the builder image itself, by using:
# # $ docker run -it nccurry/vuejs-s2i-builder --debug
[ "$1" == "--debug" ] && exec /bin/bash
