#!/usr/bin/env sh

cat <<EOF
This is a S2I base image for VueJS applications:
To use it, install S2I: https://github.com/openshift/source-to-image
Sample invocation:
s2i build https://github.com/nccurry/vuejs-s2i-builder --context-dir=test/test-vuejs-app/ nccurry/vuejs-s2i-builder:latest sample-app
You can then run the resulting image via:
docker run -p 8080:8080 sample-app
EOF
